---
title: "Reduced Rank Regression"
author: "Roger Bukuru"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, 
  message = FALSE,
  tidy=TRUE)
```

We proceed to implement Reduced Rank Regression from first principals

```{r, echo = TRUE}
rm(list= ls())
library(dplyr)
library(tidyverse)

tobacco = read.csv("../../../Data/RRR/tobacco.csv") %>%
          as.tibble()

head(tobacco)

sigma_XX = cov(tobacco[, 4:9])
sigma_XX

sigma_YY = cov(tobacco[, 1:3])
sigma_YY

X = tobacco%>%
    select(4:9)
X = t(X)
Y = tobacco%>%
    select(1:3)
Y = t(Y)

```

Calculate $\mu_x$ and $\mu_y$

```{r, echo = TRUE}
mux = apply(X, 1, mean)
muy = apply(Y, 1, mean)

mux
muy
```

Create X_c and Y_c i.e centered versions

```{r, echo = TRUE}
X_c = apply(X, 1, function(X) (X-mean(X)))
Y_c = apply(Y, 1, function(Y) (Y-mean(Y)))

```

Calculate $S_{xx}$ $S_{yy}$ & $S_{xy}$ using cross products of centered data matrices.

```{r, echo = TRUE}
#Place xc and yc back into form similar to book
X_c = t(X_c)
Y_c = t(Y_c)

n = nrow(tobacco)
Sxx = (1/(n-1))*tcrossprod(X_c)
Syy = (1/(n-1))*tcrossprod(Y_c)
Syx = (1/(n-1))*tcrossprod(Y_c, X_c) # Transpose second param i.e Y_c%*%t(X_c)
Sxy = t(Syx)
Syx

SyxSxxSxy = Syx%*%solve(Sxx)%*%Sxy ### ??
eigen1 = eigen(SyxSxxSxy)

eigen1

V = eigen1$vectors

V1 = V[,1]
V2 = V[,2]
V3 = V[,3]
A = V
B = t(V)%*%Syx%*%solve(Sxx)

A1 = matrix(V[,1], ncol = 1, byrow = TRUE) # dim 1 approx
A2 = matrix(V[,2], ncol = 1, byrow = TRUE) # dim 2 approx

B1 = matrix(B[,1], ncol = 6, byrow = TRUE) # dim 1 approx
B2 = matrix(B[,2], ncol = 6, byrow = TRUE) # dim 2 approx

C1 = A1%*%B1
C2 = A2%*%B2
C3 = A%*%B

```


# Note sure understand how A&B come into this picture



# PAH

```{r, echo. = TRUE}
library(rrr)
rm(list = ls())
pah = read.table("../../../Data/RRR/PAH.txt", header =  TRUE, sep = " ") %>%
      as.tibble()


Y = pah[,1:11] %>%
    as.matrix()

colnames(Y) = colnames(pah)[1:11]

X = pah[, 12:38]%>%
    as.matrix()

Y = t(Y)
X = t(X)

Y_c = apply(Y, 1, function(Y)(Y-mean(Y)))
X_c = apply(X, 1, function(X)(X-mean(X)))


rrr_model = rrr(x = X_c, y = Y_c, type = "identity")

  
summary(rrr_model)
coef(rrr_model)
plot(rrr_model)

```